# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 2.6.0'

gem 'bundler', '2.4.22'
gem 'dotenv', '~> 2.8'
gem 'json', '~> 2.6'

group :development do
  gem 'rubocop', '~> 1.50'
end
